name: Test

on:
  pull_request:
  push:
    branches: [main]


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: 1.19.5
          otp-version: 26

      - name: Install libvips
        run: |
          sudo apt-get updateg
          sudo apt-get install -y libvips-dev

      - name: Cache deps
        uses: actions/cache@v4
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: deps-${{ runner.os }}-

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: _build
          key: build-${{ runner.os }}-${{ env.MIX_ENV }}-${{ hashFiles('mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ env.MIX_ENV }}-

      - name: Test
        run: |
          mix deps.get
          mix compile --warnings-as-errors
          mix test
        env:
          MIX_ENV: test